services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 8080:8080
    networks:
      - app-network

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
