version: "3"

services:
  postgres:
    container_name: multimes-postgres
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  pgdata:
